#!/bin/bash 

if [ -z ${1} ]
then
    echo "Usage: jrep [PATTERN]"
    exit 1
elif [ ${1} = "--help" ] 
then
    echo "Usage: jrep [PATTERN]"
    exit 1
fi

script_path="$(realpath ${0})"
script_dir="$(dirname ${script_path})"
export CLASSPATH="${script_dir}/bin"

java comp290.Jrep "${@}"

